### ISSUE TITLE
Question related to creating a poll

### ISSUE THREAD

**Issue by mario0511** [Breee/raidquaza#6]
Hello there,

sry for contacting you guys here. I havent found a other solution to contact you.
I just have 2 simple questions:
1. for what are the "+1...+4" pre-filled reactions on every poll
2. ...and how can i disable them?

![image](https://user-images.githubusercontent.com/8446039/77827638-278d9c80-7117-11ea-9a06-a8a1d8473202.png)

Hope you can help me out. Thanks!

**Comment by Breee** [comment]
Hey there, 

By default you vote as one person. 

+1, ... +4   denotes extra persons.  

So if you want to check in with 5 people,  you would press  +4 

If you need a poll without these, I can implement it

**Comment by Breee** [comment]
closed via commit  bb9823ddf679dda00eaf86b75c51e386a1600273

You can now use `!simplepoll <title> <option1><option2>

![poll](https://user-images.githubusercontent.com/11966385/77834838-0d1fe700-7148-11ea-816c-9796402e45ba.JPG)

**Comment by mario0511** [comment]
Thanks a lot for the solution and the fast support!

**Comment by mario0511** [comment]
It would be also nice to have a "multi-word-title" without having to join the words with a dash. 
Just an idea

**Comment by Breee** [comment]
That's already possible: 

`!poll "hello this is a multiword title" "thx bro" "kk"`

You just have to enclose sentences in " ". 
The reason is, that the Bot splits the input command on space.

**Comment by mario0511** [comment]
Perfect solution! Thanks for the support. 1A
