### ISSUE TITLE
Poll is ignoring the individual nickname of the user

### ISSUE THREAD

**Issue by mario0511** [Breee/raidquaza#7]
When i check a particular option on a poll, it shows my global nickname instead of the specific nickname i entered on a particular server. Sry for my english

![image](https://user-images.githubusercontent.com/8446039/77997606-005de780-7330-11ea-8ef7-7e470c24abcf.png)

As you can see the poll shows "MarioA", when it instead should show "rui511...", as this my nickname on that server. Is it possible to change that?

**Comment by Breee** [comment]
sure, should be an easy fix

**Comment by Breee** [comment]
closed via a7209ff0965091460519eb879ec1eec0569cb3a7

**Comment by mario0511** [comment]
Once again... Many thanks from our team for the great support
